version: '3'
services:
  jewelryauction-backend:
    image: phuctth/jewelryauction:v.2
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db_jewelryauction
      MYSQL_PORT: 3306
      MYSQL_USER: phuctth
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: jewelryauction
    depends_on:
      - db_jewelryauction


  db_jewelryauction:
    image: mysql:latest
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jewelryauction
      MYSQL_USER: phuctth
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
