package com.se.jewelryauction.models.enums;

public enum JewelryStatus {
    PENDING,
    ONLINE_VALUATED,
    OFFLINE_VALUATING,
    OFFLINE_VALUATED,
    VALUATING_DELIVERING,
    STORED,
    AUCTIONING,
    PRICE_CONFIRMING,
    AUCTION_SUCCESS,
    DELIVERING,
    DELIVERED,
    AUCTION_FAIL,
    REFUNDING,
    REJECT,
    COMPLETED
}
